# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/llmer',
                'doc_host': 'https://Mchristos.github.io',
                'git_url': 'https://github.com/Mchristos/llmer',
                'lib_path': 'llmer'},
  'syms': { 'llmer.core': { 'llmer.core.LLMer': ('core.html#llmer', 'llmer/core.py'),
                            'llmer.core.LLMer.__init__': ('core.html#llmer.__init__', 'llmer/core.py'),
                            'llmer.core.LLMer.ask': ('core.html#llmer.ask', 'llmer/core.py'),
                            'llmer.core.show': ('core.html#show', 'llmer/core.py')}}}
