# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/llmer',
                'doc_host': 'https://Mchristos.github.io',
                'git_url': 'https://github.com/Mchristos/llmer',
                'lib_path': 'llmer'},
  'syms': {'llmer.core': {'llmer.core.foo': ('core.html#foo', 'llmer/core.py')}}}
